<a href="https://colab.research.google.com/github/Krish-Roorkee/ARIES_4-4-4-LED-CUBE/blob/main/rx.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from scipy.optimize import minimize

In [3]:
pip install pyswarms

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.1/104.1 kB 3.4 MB/s eta 0:00:00


In [4]:
import pyswarms as ps

In [5]:
n_truck = 3;
n_nodes = 3;
W = np.array([n_truck, n_nodes, 3,10],dtype=np.int32);


In [6]:
def obj(W, initPos, distMat, reqLoads):
 C_l = 1;
 C_d = 1/100;
 speed = 40;
 cost = 0;
 load_status = np.zeros((n_nodes, 12));
 for t in range(n_truck):
  distanceTravelled = 0;
  time = 0;
  current_P = initPos[t];
 for p in W[t]:
  time += p[0];
  load_status[int(current_P)%n_nodes][int(time)%12] += np.floor(p[1]);
  distanceTravelled += distMat[int(current_P)%n_nodes][int(p[2])%n_nodes];
  time += distMat[int(current_P)%n_nodes][int(p[2])%n_nodes]/speed;
  current_P = p[2];
  cost += distanceTravelled * C_d;
 for i in range(n_nodes):
  for h in range(12):
   cost += C_l*(np.square((reqLoads[i][h] - load_status[i][h])));
 return cost;

In [7]:
distMat = [[0, 100, 200],
           [100, 0, 240],
           [200, 240, 0]];
initPos = [0, 1, 2];
reqLoads = [[0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0],
            [0, -10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0]];

In [8]:
def g(w):
  W = np.zeros((n_truck, n_nodes, 3));
  for i in range(n_truck*n_nodes*3):
    x = i%n_truck;
    y = (i%n_truck)%n_nodes;
    z = ((i%n_truck)%n_nodes)%3;
    W[x][y][z] = w[i];
  return obj(W, initPos, distMat, reqLoads);

In [9]:
import scipy as sp;

In [11]:
options = {'c1': 0.5, 'c2': 0.3, 'w':0.9}

optimizer = ps.single.GlobalBestPSO(n_particles=1000, dimensions=27, options=options)
def f(wp):
  wp = np.abs(wp)*100;
  return np.array([g(w) for w in wp]);

cost, pos = optimizer.optimize(f, iters=1000)

2023-11-27 16:33:02,160 - pyswarms.single.global_best - INFO - Optimize for 1000 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
pyswarms.single.global_best: 100%|██████████|1000/1000, best_cost=156
2023-11-27 16:34:58,599 - pyswarms.single.global_best - INFO - Optimization finished | best cost: 156.0, best pos: [0.40732487 1.50506435 1.22854818 0.38279736 1.18014433 0.61680146
 0.33248551 0.65256746 1.31991025 1.22639047 1.12161092 0.87333287
 1.35389897 0.5311303  0.22566751 1.02117807 0.37562938 1.22279283
 0.81822278 1.4678397  0.68399794 1.14311056 1.24030292 0.63573494
 1.37461936 0.76609878 0.93538988]


In [17]:
initPos = np.random.randint(0, n_nodes, size=(n_truck,))

In [18]:
!pip install pyswarm


  Preparing metadata (setup.py) ... done
  Created wheel for pyswarm: filename=pyswarm-0.6-py3-none-any.whl size=4463 sha256=51f7fcef23e74dcc8ef187b3ec85c24fd4e7bcd1a8b4cd994923fe0e70bbaf92
  Stored in directory: /root/.cache/pip/wheels/71/67/40/62fa158f497f942277cbab8199b05cb61c571ab324e67ad0d6
Successfully built pyswarm


In [24]:
from pyswarm import pso
initPos = np.random.randint(0, n_nodes, size=(n_truck,))
def objective_function(position):
    W = np.reshape(position, (n_truck, -1, 3))
    cost = obj(W, initPos, distMat, reqLoads)
    return cost
lb = np.zeros(n_truck * len(initPos) * 3)
ub = np.ones(n_truck * len(initPos) * 3)
best_position, min_cost = pso(objective_function, lb, ub)
optimal_path = np.reshape(best_position, (n_truck, -1, 3))
print("Optimal Path:")
print(optimal_path)
print("Minimum Cost:", min_cost)




Stopping search: maximum iterations reached --> 100
Optimal Path:
[[[0.50686144 0.7134811  0.4903842 ]
  [0.83137104 0.49539951 0.91294196]
  [0.0560529  0.23950466 0.86304325]]

 [[0.1983311  0.99108652 0.40642848]
  [0.29033686 0.13558895 0.1450957 ]
  [0.08460199 0.58115647 0.02293404]]

 [[0.4777408  0.4093589  0.23416357]
  [0.40882981 0.21613003 0.28160356]
  [0.14536852 0.51416488 0.683921  ]]]
Minimum Cost: 150.0
